[build]
  publish = "public"
  command = "npm install hexo-generator-feed --save;npm i hexo-url-submission;npm install hexo-renderer-pug hexo-renderer-stylus --save;npm run build"

[build.environment]
  NODE_VERSION = "14"
